image: ruby:2.3
pages:
  stage: deploy
  script:
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - bundle install
    - bundle exec middleman build
  artifacts:
    paths:
    - public 
  only:
  - master