image: starefossen/ruby-node:2-8-slim
pages:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y build-essential
    - bundle install
    - bundle exec middleman build
  artifacts:
    paths:
    - public 
  only:
  - master